# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-MboxParser
version:      0.53
version_from: MboxParser.pm
installdirs:  site
requires:
    File::Temp:                    0
    MIME::Base64:                  0
    MIME::QuotedPrint:             0
    MIME::Tools:                   5

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
